### ISSUE TITLE
Encoding unsupported while JSON parsing

### ISSUE THREAD

**Issue by hekike** [cojs/co-body#26]
I got this error after updating to 3.0.0.
I do simple `yield parse(this);` with `koa`.
Any idea?

```
Error: specified encoding unsupported
      at makeError (/Users/pmarton/Documents/dev/experiment-service/node_modules/co-body/node_modules/raw-body/index.js:198:15)
      at getDecoder (/Users/pmarton/Documents/dev/experiment-service/node_modules/co-body/node_modules/raw-body/index.js:170:15)
      at module.exports (/Users/pmarton/Documents/dev/experiment-service/node_modules/co-body/node_modules/raw-body/index.js:75:15)
      at Object.<anonymous> (/Users/pmarton/Documents/dev/experiment-service/node_modules/co-body/lib/json.js:36:5)
```

**Comment by coderhaoxin** [comment]
Everything is OK with `co-body < 3.0.0` ?

**Comment by hekike** [comment]
@coderhaoxin yes!

**Comment by coderhaoxin** [comment]
Can you print the full error message? Such as: `err.encoding`

**Comment by coderhaoxin** [comment]
Reopen if the problem still exists.
