### ISSUE TITLE
Unsupported content-type: application/json;charset=utf-8 with DELETE method?

### ISSUE THREAD

**Issue by youngerheart** [cojs/co-body#47]
```
Error: Unsupported content-type: application/json;charset=utf-8
      at module.exports (/Users/younger/Develop/grail/node_modules/co-body/lib/any.js:47:13)
      at _callee$ (/Users/younger/Develop/grail/node_modules/clannad/dist/app.js:63:41)
      at tryCatch (/Users/younger/Develop/grail/node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/younger/Develop/grail/node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/younger/Develop/grail/node_modules/regenerator-runtime/runtime.js:95:21)
      at step (/Users/younger/Develop/grail/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/younger/Develop/grail/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at new Promise (/Users/younger/Develop/grail/node_modules/core-js/library/modules/es6.promise.js:193:7)
      at /Users/younger/Develop/grail/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
      at /Users/younger/Develop/grail/node_modules/clannad/dist/app.js:126:16
      at dispatch (/Users/younger/Develop/grail/node_modules/koa-compose/index.js:43:32)
      at /Users/younger/Develop/grail/node_modules/koa-compose/index.js:36:12
      at Server.<anonymous> (/Users/younger/Develop/grail/node_modules/clannad/node_modules/koa/lib/application.js:135:7)
      at emitTwo (events.js:100:13)
      at Server.emit (events.js:185:7)
      at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:537:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
```

**Comment by youngerheart** [comment]
`parse()` is not useful and show error like I say, so I have to use like this

```
let type = ctx.headers['content-type'];
if (type.indexOf('application/json') > -1)
  ctx.req.body = await parse.json(ctx) || {};
else if (type.indexOf('application/x-www-from-urlencoded') > -1)
  ctx.req.body = await parse.form(ctx) || {};
else ctx.req.body = await parse(ctx) || {};
```

but document say `parse()` is either, am i wrong in usage?

**Comment by coderhaoxin** [comment]
@youngerheart can you print your request's `header` and `body`?
